# Python recap

**Table of contents**<a id='toc0_'></a>    
- 1. [Classes](#toc1_)    
- 2. [References](#toc2_)    
- 3. [Types and in-place operations](#toc3_)    
- 4. [Functions and scope](#toc4_)    
- 5. [Conditionals and loops](#toc5_)    
- 6. [Decimal numbers are not exact](#toc6_)    
- 7. [Random numers](#toc7_)    

<!-- vscode-jupyter-toc-config
	numbering=true
	anchor=true
	flat=false
	minLevel=2
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [1]:
import numpy as np

## 1. <a id='toc1_'></a>[Classes](#toc0_)

In [2]:
class Parent:

    def __init__(self,value):
        self.value = value

    def double(self):
        return self.value * 2
    
class Child(Parent):

    def half(self):
        return self.value / 2
    
child = Child(10)
print(child.value)
print(child.double())
print(child.half())

10
20
5.0


## 2. <a id='toc2_'></a>[References](#toc0_)

In [3]:
a = np.array([1,2,3])
b = a
c = a[1:] # slicing
b[0] = 3 # indexing
c[0] = 3
print(a)

[3 3 3]


Same with a list?

In [4]:
a = [1,2,3]
b = a
c = a[1:] # slicing (copy)
b[0] = 3 # indexing
c[0] = 3
print(a)

[3, 2, 3]


## 3. <a id='toc3_'></a>[Types and in-place operations](#toc0_)

In [5]:
x = np.array([1,2,3])
y = x
x += 1
x[:] = x + 1
x = x + 1
print(x)

[4 5 6]


**Functions and scope:**

In [6]:
a = 1
def f(x):
	return x+a
print(f(1))
a = 2
print(f(1))

2
3


## 4. <a id='toc4_'></a>[Functions and scope](#toc0_)

In [ ]:
a = 1
def f(x):
	return x+a
print(f(1))
a = 2
print(f(1))

2
3


## 5. <a id='toc5_'></a>[Conditionals and loops](#toc0_)

In [7]:
x0 = 1
n = 4
evaluate = lambda x: 0.5*x
check = lambda y: y < 0.10
update = lambda x,y: y

x = x0
for i in range(n):
    y = evaluate(x)
    if check(y): break
    x = update(x,y)
else:
    raise ValueError('did not converge')

In [8]:
x = x0
i = 0
while True:
    y = evaluate(x)
    if check(y): break
    x = update(x,y)
    i += 1
    if i >= n:
        raise ValueError('did not converge')

## 6. <a id='toc6_'></a>[Decimal numbers are not exact](#toc0_)

In [9]:
print(0.1 + 0.2 == 0.3)
print(0.5 + 0.5 == 1.0)

False
True


## 7. <a id='toc7_'></a>[Random numers](#toc0_)

In [10]:
print(np.isclose(0.1+0.2,0.3))

True


In [11]:
a = 1e-200*1e200*1e200*1e-200
b = 1e-200*(1e200*1e200)*1e-200
c = 1e200*(1e-200*1e-200)*1e200

print(np.isclose(a,1.0))
print(np.isinf(b))
print(np.isclose(c,0.0))

True
True
True


In [12]:
rng = np.random.default_rng(123)
s = rng.bit_generator.state
x = rng.normal(size=5)
y = rng.normal(size=5)
rng.bit_generator.state = s
z = rng.normal(size=5)
print(x)
print(y)
print(z)

[-0.98912135 -0.36778665  1.28792526  0.19397442  0.9202309 ]
[ 0.57710379 -0.63646365  0.54195222 -0.31659545 -0.32238912]
[-0.98912135 -0.36778665  1.28792526  0.19397442  0.9202309 ]


Old style:

In [13]:
np.random.seed(123)
s = np.random.get_state()
x = np.random.normal(size=5)
y = np.random.normal(size=5)
np.random.set_state(s)
z = np.random.normal(size=5)
print(x)    
print(y)
print(z)

[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025]
[ 1.65143654 -2.42667924 -0.42891263  1.26593626 -0.8667404 ]
[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025]
